# Generated by Django 5.2.11 on 2026-03-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_voice_author_voice_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='是否公开'),
        ),
    ]
