# Generated by Django 5.2.11 on 2026-03-25 07:03

import web.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_character_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='app_background',
            field=models.ImageField(default='user/app_backgrounds/default.png', upload_to=web.models.user.app_background_upload_to, verbose_name='系统背景'),
        ),
    ]
