# Generated by Django 5.2.11 on 2026-04-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_userprofile_app_background'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='出生日期'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='id_card_number',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='身份证号'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_minor',
            field=models.BooleanField(default=False, verbose_name='是否未成年'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='是否已实名'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='real_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='真实姓名'),
        ),
    ]
