# Generated by Django 5.2.11 on 2026-04-24 10:32

import web.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_userprofile_birth_date_userprofile_id_card_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='id_card_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='身份证哈希防重'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id_card_number',
            field=web.fields.EncryptedCharField(blank=True, max_length=255, null=True, verbose_name='身份证号'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='real_name',
            field=web.fields.EncryptedCharField(blank=True, max_length=255, null=True, verbose_name='真实姓名'),
        ),
    ]
