# Generated by Django 5.2.11 on 2026-05-08 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_userprofile_id_card_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='avatar_type',
            field=models.CharField(choices=[('none', '无'), ('male', '男性'), ('female', '女性'), ('dog', '小狗'), ('cat', '小猫')], default='none', max_length=20, verbose_name='3D模型类型'),
        ),
    ]
